name: 🐞 Bug report
description: "Report a bug or something that is otherwise not working as expected."
labels: ["bug"]

body:
  - type: checkboxes
    id: diagnostics
    attributes:
      label: Diagnostic Checklist
      description: "Check these common causes to rule out basic configuration or setup issues."
      options:
        - label: "Tado [iPhone](https://apps.apple.com/gb/app/tado/id574418486) or [Android](https://play.google.com/store/apps/details?id=com.tado) app can control the device."
        - label: "Searched for [previously reported issues](https://github.com/thoukydides/matterbridge-tado-hw/issues?q=is%3Aissue) and found none."
    validations:
      required: false
      
  - type: textarea
    id: description
    attributes:
      label: Description of Issue
      description: "Provide a clear and concise description of the bug."
      placeholder: "Describe what is going wrong, the symptoms, the frequency, and any recent changes..."
    validations:
      required: true
    
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: "Provide a step-by-step description of how to reproduce the issue."
      placeholder: |
        Steps to reproduce:
        1. ...
        2. ...
    validations:
      required: true
  
  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: "State the plugin version exhibiting the bug. If not using the latest version, please update before reporting."
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Describe the software environment being used to run this plugin. Include:
        - Operating System type and version (output of `lsb_release -d` on Linux)
        - Node.js version (output of `node -v` or reported in Matterbridge frontend)
        - Matterbridge version (output of `npm -g ls matterbridge` or reported in Matterbridge frontend)
      placeholder: |
        - OS: e.g. Ubuntu 24.04.1 LTS or macOS Ventura 13.5
        - Node: e.g. v18.20.4
        - Matterbridge: e.g. 3.0.0
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Tado° Device(s)
      description: |
        Provide the device name, model number, and firmware version.
      placeholder: "e.g. Extension Kit V3P-EK01-TC-ML firmware 81.1"
    validations:
      required: false
      
  - type: input
    id: mattercontroller
    attributes:
      label: Matter Controller(s)
      description: "Provide details of the Matter controller(s) being used, including their versions."
      placeholder: "e.g. Apple Home iOS 18.4, Amazon Alexa, Google Home, Samsung SmartThings, Home Assistant 2025.4.3, etc."
    validations:
      required: false
      
  - type: textarea
    id: log
    attributes:
      label: Log File
      description: |
        Provide relevant Matterbridge logs, either pasted below or attached as a text file. Do NOT use a screenshot. Replace sensitive information (access tokens, etc) with `REDACTED`. Logs are most useful when they are complete; include the full output around the error message and do not omit any lines.

        Enable and capture appropriate extra debug:
        
        - **For Plugin Debug Logging** (enable for most issues):
          - In Matterbridge frontend: *Home* > *Plugins* > *matterbridge-tado-hw* > ⚙️ > *debug* > ✅
            - Or in the `matterbridge-tado-hw.config.json` file: `"debug": true`
          - View the log file directly (e.g. `journalctl -u matterbridge.service -n 1000 -f --output cat`); the Matterbridge frontend normally filters out debug messages.
          
        - **For Matterbridge Logging**:
          - In Matterbridge frontend: *Settings* > *Matterbridge settings* > *Logger level* > *Debug*.
            - Or add `-logger debug` to the `matterbridge` command line.
          
        - **For Matter Logging**:
          - In Matterbridge frontend: *Settings* > *Matter settings* > *Logger level* > *Debug*.
            - Or add `-matterlogger debug` to the `matterbridge` command line.
        
        The additional debug information in the logs will provide more context for resolving your issue.
      placeholder: |
        Paste the logs...
      render: shell
    validations:
      required: true

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: "Provide your `matterbridge-tado-hw.config.json` (if relevant). This is optional but highly recommended. Replace any sensitive information with `REDACTED`."
      placeholder: "Paste configuration..."
      render: json
    validations:
      required: false
   
  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: "Provide any additional information that might assist with resolving your bug report. This could include links to product web pages, user manuals, screenshots, videos, or anything else relevant. If you have tried workarounds or debugging steps, include them here."
      placeholder: "Any other relevant information..."
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        **Important Notes:**
        - ⚠️ Ensure all required fields are filled.
        - 🐞 Debug logs are crucial for resolving most issues - please include them.
        - 🔐 Ensure sensitive information like tokens or passwords are `REDACTED` before sharing.
        - 🔄 If you are not using the most recent plugin version, update before submitting.