name: Prepare Environment
description: Prepare build environment with selected Matterbridge installation

inputs:
  node-version:
    required: false
    default: 20.x

  matterbridge-tag:
    required: false
    default: 'latest'

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ inputs.node-version }} 
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'
          
    - name: Update npm
      shell: bash
      run: npm install -g npm@latest

    - name: Install project dependencies
      shell: bash
      run: npm ci

    - name: Install Matterbridge from npm
      shell: bash
      run: npm run setup-matterbridge
      env:
        MATTERBRIDGE_TAG: ${{ inputs.matterbridge-tag }}