name: Prepare Environment

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: 18.x

  use-matterbridge-edge:
    description: If true, clone Matterbridge from GitHub edge branch
    required: false
    default: 'true'

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ inputs.node-version }} 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install project dependencies
      shell: bash
      run: npm ci

    - name: Setup Matterbridge (${{ inputs.use-matterbridge-edge == 'true' && 'edge' || 'npm' }})
      id: matterbridge
      shell: bash
      run: |
        set -e
        if [[ "${{ inputs.use-matterbridge-edge }}" == "true" ]]; then
          echo "🔧 Cloning Matterbridge from GitHub..."
          MATTERBRIDGE_DIR="$RUNNER_TEMP/matterbridge" npm run setup-matterbridge-edge
        else
          echo "📦 Installing Matterbridge from npm..."
          npm run setup-matterbridge-npm
        fi