name: Prepare Environment

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: 20.x

  matterbridge-branch:
    description: If set, clone Matterbridge from the specified GitHub branch
    required: false
    default: ''

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ inputs.node-version }} 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install project dependencies
      shell: bash
      run: npm ci

    - name: Install Matterbridge from npm
      if: ${{ inputs.matterbridge-branch == '' }}
      shell: bash
      run: npm run setup-matterbridge-npm

    - name: Install Matterbridge from GitHub
      if: ${{ inputs.matterbridge-branch != '' }}
      shell: bash
      run: npm run setup-matterbridge-github
      env:
        MATTERBRIDGE_DIR: ${{ runner.temp }}/matterbridge
        MATTERBRIDGE_BRANCH: ${{ inputs.matterbridge-branch }}