name: Prepare Environment

inputs:
  node-version:
    description: Node.js version to use
    required: false
    default: 20.x

runs:
  using: composite

  steps:
    - name: Use Node.js ${{ inputs.node-version }} 
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install project dependencies
      shell: bash
      run: npm run setup