name: Build and Lint
permissions:
  contents: read

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '15 7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x]
        matterbridge-branch: ['', 'dev']

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
  
      - name: Prepare build environment
        uses: ./.github/actions/prepare-environment
        with:
          node-version: ${{ matrix.node-version }}
          matterbridge-branch: ${{ matrix.matterbridge-branch }}

      - name: Build the project
        run: npm run build

      - name: Lint the project
        run: npm run lint