name: Build and Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        use-matterbridge-edge: [true, false]

    steps:
      - name: Checkout project
        uses: actions/checkout@v4
  
      - name: Prepare build environment
        id: prepare
        uses: ./.github/actions/prepare-environment
        with:
          node-version: ${{ matrix.node-version }}
          use-matterbridge-edge: ${{ matrix.use-matterbridge-edge }} 

      - name: Build the project
        run: npm run build

      - name: Lint the project
        run: npm run lint